[package]
name = "gk-test"
version = "0.1.0"
authors = ["llgoer <llgoer@github.com>"]
edition = "2018"
description = "simple rust lib"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
